### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by frmdstryr** [V-E-O/czipfile#1]
Hi,

Do you have any benchmarks (or even just a general idea) of how much faster this is? 

Could this be used with the builtin zipimporter?

Thanks!

**Comment by V-E-O** [comment]
Sorry, I'm not the author, the original repo is here: https://pypi.python.org/pypi/czipfile/1.0.0
I just did some update and fixed a few bugs.
Cython may be accelerating it a bit, but not much, mainly costs in IO, and zip decoding.
It is stable by far.

**Comment by frmdstryr** [comment]
No worries, thanks.
